---
title: "jstanfield-participation-week5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plotly)
library(ggplot2)
library(tidyverse)
```

```{r}
head(diamonds)


```

```{r}
diamonds.sample <- sample_n(diamonds, 10000)
```


```{r}
#plot_ly(data = diamonds, x = ~carat, y = ~price)
#plot_ly(data = diamonds, x = ~cut, y = ~price)


diamonds %>%
  sample_n(100) %>%
plot_ly(data = ., x = ~carat, y = ~price, type = "scatter")
```

```{r}

plot_ly(data = diamonds.sample, x = ~carat, y = ~price) %>% 
  add_trace(p =., type = "scatter")

```

### styling

```{r}

plot_ly(data = diamonds, x = ~carat, y = ~price) %>% 
  add_trace(p = ., type = "scatter") %>% 
  layout(xaxis = list(range = c(2.5, 5), title = "Carat"), 
         yaxis = list(title = "Price"))

```


```{r}
plot_ly(data = diamonds, x = ~carat, y = ~price, text = ~paste0("Price:$", price, "<br>Carat:", carat)) %>% 
  add_trace(p = ., type = "scatter") %>% 
  layout(xaxis = list(range = c(2.5, 5), title = "Carat"), 
         yaxis = list(title = "Price"))
```

```{r}

lines.data <- data.frame(x = c(1:100), trace0 = rnorm(100, mean = 5)) %>% 
  mutate(trace1 = log(trace0), trace2 = trace0^2)

#pivot_longer(data = lines.data, names_to = "trace", values_to = "val")

line.wide <- gather(data = lines.data, key = "trace", value = "val", -x)

```

```{r}
plot_ly(data = lines.data, x = ~x) %>% 
  add_trace(y = ~trace0, name = "Trace Zero", mode = 'lines') %>% 
  add_trace(y = ~trace1, name = "Trace One", mode = 'lines') %>% 
  add_trace(y = ~trace2, name = "Trace Two", mode = 'lines')
```

```{r}
plot_ly(data = line.wide, x = ~x, y = ~val, color = ~trace, mode = "line") 
```

```{r}
plot_ly(data = line.wide, x = ~x, y = ~val, color = ~trace, mode = "lines+markers") 
```

```{r}
plot_ly(data = line.wide, x = ~x, y = ~val, color = ~trace, mode = "lines+markers") %>% 
  layout(xaxis = list(ticks = "outside",
                      dtick = 10,
                      ticklen = 5,
                      tickwidth = 2,
                      tickcolor = toRGB("pink"),
                      title = "X",
                      showgrid = FALSE,
                      zeroline = FALSE),
         yaxis = list(ticks = "outside",
                      dtick = 5,
                      ticklen = 10,
                      tickwidth = 1,
                      tickcolor = toRGB("pink"),
                      title = "Val",
                      showgrid = FALSE,
                      zeroline = FALSE),
         showlegend = TRUE,
         legend = list(x = .17, y = .99), #list(orientation = 'h') to place at bottom
         title = "Fake Data") 
```

```{r}

cnt <- with(diamonds.sample, table(cut, clarity))

plot_ly(data = diamonds.sample, x = ~cut, y = ~clarity, z = ~cnt) %>% 
  add_trace(type = "histogram2dcontour",
            contours = list(showlabels = T, labelfont = list(color = 'white'))) #this line just adds the labels

```

```{r}
plot_ly(data = diamonds.sample, y = ~price, color = ~cut, type = "box")


```

### 3d plot

```{r}

plot_ly(data = diamonds.sample, x = ~carat, y = ~price, z = ~depth, color = ~cut)

```

```{r}

fig1 <- diamonds.sample %>% 
  ggplot(data = ., aes(x = price, y = depth, color = cut)) +
  geom_point() #make a ggplot

ggplotly(fig1) #send your ggplot to plotly for interactivity
```






















